import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'
import { supabase } from '@/lib/supabase'

export async function POST(request: NextRequest) {
  let body: {
    email: string
    auditId: string
    companyName?: string
    role?: string
    teamSize?: number
    monthlySavings?: number
    website?: string // honeypot
  }

  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  // Honeypot check — bots fill the "website" field
  if (body.website) {
    // Silently accept but don't process (don't tell the bot it failed)
    return NextResponse.json({ success: true })
  }

  const { email, auditId, companyName, role, teamSize, monthlySavings } = body

  if (!email || !email.includes('@')) {
    return NextResponse.json({ error: 'Invalid email' }, { status: 400 })
  }

  // Save lead to Supabase
  if (supabase) {
    try {
      await supabase.from('leads').insert({
        audit_id: auditId,
        email,
        company_name: companyName ?? null,
        role: role ?? null,
        team_size: teamSize ?? null,
        created_at: new Date().toISOString(),
      })
    } catch {
      console.error('Lead save failed')
    }
  }

  // Send transactional email via Resend
  const resendKey = process.env.RESEND_API_KEY
  if (resendKey) {
    try {
      const resend = new Resend(resendKey)
      const isHighSavings = (monthlySavings ?? 0) > 500

      await resend.emails.send({
        from: 'StackAudit <audit@stackaudit.com>',
        to: email,
        subject: `Your AI spend audit${monthlySavings ? ` — $${monthlySavings}/mo in savings found` : ''}`,
        html: `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width"></head>
<body style="font-family: 'Georgia', serif; background: #f5f0e8; margin: 0; padding: 40px 20px;">
  <div style="max-width: 560px; margin: 0 auto; background: white; border: 1px solid #d4cfc6; padding: 48px;">
    <div style="font-size: 11px; text-transform: uppercase; letter-spacing: 2px; color: #6b6b6b; margin-bottom: 32px;">StackAudit</div>
    
    <h1 style="font-size: 26px; color: #0a0a0a; margin: 0 0 16px; font-weight: 400; line-height: 1.3;">
      Your audit is ready.
    </h1>
    
    ${
      monthlySavings && monthlySavings > 0
        ? `<p style="font-size: 18px; color: #e63946; font-weight: 600; margin: 0 0 24px;">
            $${monthlySavings}/mo · $${monthlySavings * 12}/year in potential savings
           </p>`
        : `<p style="font-size: 16px; color: #0a0a0a; margin: 0 0 24px;">
            Good news: your AI stack is already well-optimized.
           </p>`
    }
    
    <p style="color: #3a3a3a; line-height: 1.7; margin: 0 0 24px;">
      We've run your tools through our audit engine. Your full breakdown is waiting at the link you were viewing — bookmark it to reference later.
    </p>
    
    ${
      isHighSavings
        ? `<div style="background: #f5f0e8; border-left: 3px solid #e63946; padding: 16px 20px; margin: 0 0 24px;">
            <strong style="display: block; margin-bottom: 6px; color: #0a0a0a;">You qualify for a Credex consultation.</strong>
            <p style="color: #3a3a3a; margin: 0; font-size: 14px; line-height: 1.6;">With $${monthlySavings}/mo in savings potential, a Credex advisor can help you capture these savings through AI credit strategies. They'll reach out within 2 business days.</p>
          </div>`
        : ''
    }
    
    <p style="color: #6b6b6b; font-size: 13px; line-height: 1.6; margin: 32px 0 0; border-top: 1px solid #d4cfc6; padding-top: 24px;">
      This audit was generated by StackAudit, a tool by Credex. Pricing data verified ${new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}.
    </p>
  </div>
</body>
</html>`,
      })
    } catch {
      console.error('Resend email failed')
    }
  }

  return NextResponse.json({ success: true })
}
